routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');
Route::get('index','FrontController@index');
Route::get('register','FrontController@register');
//Route::get('login','FrontController@lo');
Route::get('maleRegister','FrontController@MaleRegisterForm');
Route::post('maleRegister','FrontController@MaleRegister');
Route::get('femaleRegister','FrontController@FemaleRegisterForm');
Route::post('femaleRegister','FrontController@FemaleRegister');
Route::get('city/{id}','FrontController@city');
Route::get('email/{id}','FrontController@email');
Route::get('username/{id}','FrontController@username');
Route::get('phone/{id}','FrontController@phone');
Route::get('salary/{id}','FrontController@salary');
Route::get('height/{id}','FrontController@height');
Route::get('weight/{id}','FrontController@weight');
Route::post('/client/home','ClientAuth\LoginController@login');
Route::get('/test','FrontController@pricesValues');
Route::get('liked', 'FrontController@likes');
Route::get('blocked', 'FrontController@blocked');
Route::get('/cancelBlock/{id}', 'LikesController@cancelBlock');
Route::get('/search', 'FastSearchController@search');
Route::get('/profile_views/{id}', 'ProfileViewController@addView');

  Route::get('/admin/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
  Route::post('/admin/login', 'AdminAuth\LoginController@login');

Route::group(['prefix' => 'admin', 'middleware'=>'admin'], function () {
  Route::get('/logout', 'AdminAuth\LoginController@logout')->name('logout');
  Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'AdminAuth\RegisterController@register');

  //clients
  Route::get('/users', 'dashboard\ClientsController@index');
  Route::get('/approve/{id}', 'dashboard\ClientsController@approve');
  Route::get('/unapprove/{id}', 'dashboard\ClientsController@block');
  Route::get('/upgrage/{id}', 'dashboard\ClientsController@upgrage');
  Route::get('/details/{id}', 'dashboard\ClientsController@show');
  Route::get('/edit_user/{id}', 'dashboard\ClientsController@edit');
  Route::patch('/updateUser/{id}', 'dashboard\ClientsController@update');
  Route::get('/fakeData', 'dashboard\ClientsController@fakers');
  Route::get('/country', 'dashboard\ClientsController@country');
  Route::get('/delete/{id}', 'dashboard\ClientsController@destroy');
  Route::get('/country/city/{id}', 'dashboard\ClientsController@city');
  Route::get('/all_users', 'dashboard\ClientsController@forExcel');

  //messages
  Route::get('/send_message/{id}', 'dashboard\MessageToClientsController@index');
  Route::get('/send/message', 'dashboard\MessageToClientsController@sendMessage');

  //site info
  Route::get('/site_info', 'dashboard\SiteInfoController@index');
  Route::get('/add_site_info', 'dashboard\SiteInfoController@create');
  Route::get('/edit_info/{id}', 'dashboard\SiteInfoController@edit');
  Route::get('/delete_info/{id}', 'dashboard\SiteInfoController@destroy');
  Route::patch('/updateSiteInfo/{id}', 'dashboard\SiteInfoController@update');

  //about us
  Route::get('/about-us', 'dashboard\OtherSiteInfoController@showAboutUs');
  Route::get('/edit_about_us/{id}', 'dashboard\OtherSiteInfoController@editAboutUs');
  Route::patch('/updateAboutUs/{id}', 'dashboard\OtherSiteInfoController@updateAboutUs');

  //Contact us
  Route::get('/contact_us', 'dashboard\OtherSiteInfoController@showContactUs');
  Route::get('/edit_contact_us/{id}', 'dashboard\OtherSiteInfoController@editContactUs');
  Route::patch('/updateContactUs/{id}', 'dashboard\OtherSiteInfoController@updateContactUs');

  //FAQS
  Route::get('/faqs', 'dashboard\OtherSiteInfoController@showFAQ');
  Route::get('/edit_faqs/{id}', 'dashboard\OtherSiteInfoController@editFAQ');
  Route::patch('/updateFAQS/{id}', 'dashboard\OtherSiteInfoController@updateFAQ');
  Route::get('/createFaqs', 'dashboard\OtherSiteInfoController@createFAQ');
  Route::post('/storeFaq', 'dashboard\OtherSiteInfoController@storeFAQ');
  Route::get('/delete_faq/{id}', 'dashboard\OtherSiteInfoController@destroyFaq');

  //MailBox
  Route::get('/mailbox', 'dashboard\MessageToClientsController@seeAll');
  Route::get('/message', 'MailController@index');

  Route::resource('mail', 'MailController');


  //resets
  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');

  Route::resource('country','CountryController');
  Route::resource('city','CityController');
});

Route::group(['prefix' => 'client'], function () {
  // Route::post('/login', 'ClientAuth\LoginController@login');
  Route::get('/logout', 'ClientAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'ClientAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'ClientAuth\RegisterController@register');

  Route::get('/edit', 'UserController@edit');
  Route::patch('/update/{id}', 'UserController@update');

  Route::get('/contact', 'dashboard\MessageToClientsController@showForm');
  Route::post('/toAdmin', 'dashboard\MessageToClientsController@postContact');

  Route::get('/faq', 'CityController@FAQ');
  Route::get('/profile/{id}', 'FrontController@profile');
  //messages
  Route::get('/message', 'UserController@showCoversations');
  Route::get('/message/{id}', 'UserController@viewMessages');
  Route::post('/message', 'UserController@sendMessage');

  
  Route::get('/nsay7', 'CityController@advice');
  Route::get('/country/city/{id}', 'dashboard\ClientsController@city');

  //add like
  Route::get('/like/{id}', 'LikesController@addLike');

  //add block
  Route::get('/block/{id}', 'LikesController@addBlock');

  //visits
  Route::get('/visits','ProfileViewController@visits');
  
  //Advanced Search
  Route::get('/advanced_search', 'FastSearchController@advanced_search');
  Route::get('/AS', 'FastSearchController@advanced_search_results');
  
  Route::post('/password/email', 'ClientAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'ClientAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'ClientAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'ClientAuth\ResetPasswordController@showResetForm');
});

resources/views/admin/aboutUsShow.blade.php
@extends('admin.master')
@section('content')
@if($flash = session('message'))
<div class="alert success">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
    <b>{{ $flash }}</b>
</div>
@endif
@if($flash = session('deleted'))
<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
    <b>{{ $flash }}</b>
</div>
@endif

<div class="box">
            <div class="box-header">
  <h3 class="box-title">Data Table For About Us</h3>
</div>
    <div class="box-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Desc</th>
          <th>Edit</th>
        </tr>
        </thead>
        <tbody>
@foreach($about_us as $a)
        <tr>
          <td>{{ $a->id }}</td>
          <td>{{ $a->title }}</td>
          <td><?= $a->desc ?></td>
          <td>
            <a href="/admin/edit_about_us/{{ $a->id }}" class="btn btn-app">
                 <i class="fa fa-edit"></i> Edit
            </a>
          </td>
        </tr>
@endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/admin/contactUsShow.blade.php
@extends('admin.master')
@section('content')
@if($flash = session('message'))
<div class="alert success">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
    <b>{{ $flash }}</b>
</div>
@endif
@if($flash = session('deleted'))
<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
    <b>{{ $flash }}</b>
</div>
@endif

<div class="box">
            <div class="box-header">
  <h3 class="box-title">Data Table For Contact Us</h3>
</div>
    <div class="box-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>ID</th>
          <th>Address</th>
          <th>Phone 1</th>
          <th>Phone 2</th>
          <th>Edit</th>
        </tr>
        </thead>
        <tbody>
@foreach($contact_us as $c)
        <tr>
          <td>{{ $c->id }}</td>
          <td>{{ $c->address }}</td>
          <td>{{ $c->phone1 }}</td>
          <td>{{ $c->phone2 }}</td>
          <td>
            <a href="/admin/edit_contact_us/{{ $c->id }}" class="btn btn-app">
                 <i class="fa fa-edit"></i> Edit
            </a>
          </td>
        </tr>
@endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/admin/createFAQ.blade.php
@extends('admin.master')
@section('content')

<form method="POST" action="/admin/storeFaq">
	{{ csrf_field() }}
<div class="box box-danger">
            <div class="box-header with-border">
              <h3 class="box-title">Create Site FAQ</h3>
            </div>
	<div class="form-group has-success">
	  <label class="control-label" for="inputSuccess"><i class="fa fa-check"></i> Question</label>
	  <input type="text" class="form-control" name="question" id="inputSuccess">
	  <span class="help-block">Must Be Deep &amp; Decribtive</span>
	</div>
   <div class="box box-info">
    <div class="box-header">
      <h3 class="box-title">Answer
      </h3>
      <div class="pull-right box-tools">
        <button type="button" class="btn btn-info btn-sm" data-widget="collapse" data-toggle="tooltip"
                title="Collapse">
          <i class="fa fa-minus"></i></button>
        <button type="button" class="btn btn-danger btn-sm" data-widget="remove" data-toggle="tooltip"
                title="Remove">
          <i class="fa fa-times"></i></button>
      </div>
    </div>
    <div class="box-body pad">
            <textarea id="editor1" name="answer" rows="10" cols="80">
            </textarea>
    </div>
  </div>
<div class="box-footer">
<button type="submit" class="btn btn-primary btn-block btn-flat">Create Site's FAQ</button>
</div>
</form>
@if(count($errors))
<div class="alert alert-danger">
<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>
</div>
@endif
@endsection

resources/views/admin/edit.blade.php
@extends('admin.master')
@section('content')
    <div class="row">
        <div class="col-md-12">
            @if ($errors->any())
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Error!</h4>
                    @foreach($errors->all() as $error)
                        <p>* {{ $error }}</p>
                    @endforeach
                </div>
            @endif
            @if (Session::has('message'))
            <!-- Modal -->
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> Successful</h4>
                    @if (Session::has('message'))
                        <p>{{ Session::get('message') }}</p>
                    @endif
                </div>
            @endif
            @if(isset($country))
                <form action="{{ route('country.update',$country->id) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('patch') }}
                    <div class="box box-danger">
                        <div class="box-header">
                            <h3 class="box-title">Edit Country : {{ $country->name }}</h3>
                        </div>
                        <div class="box-body">
                            <div class="form-group">
                                <label>Country Name</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-pencil"></i>
                                    </div>
                                    <input type="text" class="form-control" name="name" value="{{ $country->name }}" placeholder="Country Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label>currency</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-money"></i>
                                    </div>
                                    <input type="text" class="form-control" name="currency" value="{{ $country->currency }}" placeholder="Currancy">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <button type="submit" class="btn btn-block btn-primary btn-lg">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="content-wrapper" style="margin-left:0">
                    <!-- Content Header (Page header) -->
                    <!-- Main content -->
                    <section class="content">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="box">
                                    <div class="box-header">
                                        <h3 class="box-title">Data Table With Full Features</h3>
                                    </div>
                                    <!-- /.box-header -->
                                    <div class="box-body">
                                        <table id="example1" class="table table-bordered table-striped">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>City Name</th>
                                                    <th>Date</th>
                                                    <th>Control</th>
                                                </tr>
                                            </thead>
                                            <?php
                                            $i=1;
                                            ?>
                                            @foreach($country->cities as $city)
                                                <tr>
                                                    <td>{{ $i }}</td>
                                                    <td>{{ $city->name }}</td>
                                                    <td>{{ $city->created_at }}</td>
                                                    <td>
                                                        <a href="{{ url('admin/city/'. $city->id . '/edit') }}"  class="btn btn-success"><i class="fa fa-edit"> Edit</i></a>
                                                        <form action="{{url('admin/city/'. $city->id) }}" method="post" style="display: inline;">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button type="submit" class="btn btn-danger"> <i class="fa fa-remove">X</i></button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </table>
                                    </div>
                                    <!-- /.box-body -->
                                </div>
                                <!-- /.box -->
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </section>
                        <!-- /.content -->
                    </div>
            @endif
            @if(isset($countryCity))

                <form action="{{ route('city.update',$countryCity->id) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('patch') }}
                    <div class="box box-danger">
                        <div class="box-header">
                            <h3 class="box-title">Edit City : {{ $countryCity->name }}</h3>
                        </div>
                        <div class="box-body">
                            <div class="form-group">
                                <label>City Name</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-pencil"></i>
                                    </div>
                                    <input type="text" class="form-control" name="name" value="{{ $countryCity->name }}" placeholder="City Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Choose Country</label>
                                <select class="form-control" name="country_id">
                                    <option  value="">Please Choose Country</option>
                                    @foreach($cntry as $country)
                                        <option value="{{ $country->id }}" @if($countryCity->country->id == $country->id) {{ 'selected' }} @endif>{{ $country->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <div cl    ass="input-group">
                                    <button type="submit" class="btn btn-block btn-primary btn-lg">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            @endif
        </div>
    </div>
@endsection

resources/views/admin/editContactUs.blade.php
@extends('admin.master')
@section('content')

<form method="POST" action="/admin/updateContactUs/{{ $contact->id }}"  enctype="multipart/form-data">
	{{ csrf_field() }}
  <input type="hidden" name="_method" value="PATCH">
<div class="box box-danger">
            <div class="box-header with-border">
              <h3 class="box-title">Edit Site Contact Us</h3>
            </div>
	<div class="form-group has-success">
	  <label class="control-label" for="inputSuccess"><i class="fa fa-check"></i> Address</label>
	  <input type="text" class="form-control" name="address" id="inputSuccess" value="{{ $contact->address }}">
	  <span class="help-block">Current Address of the Company</span>
	</div>
  <div class="input-group">
    <div class="input-group-addon">
     1st <i class="fa fa-phone"></i>
    </div>
    <input name="phone1" type="text" class="form-control" value="{{ $contact->phone1 }}">
  </div>
  <div class="input-group">
    <div class="input-group-addon">
     2nd <i class="fa fa-phone"></i>
    </div>
    <input name="phone2" type="text" class="form-control" value="{{ $contact->phone2 }}">
  </div>
<div class="box-footer">
<button type="submit" class="btn btn-success btn-block btn-flat">Edit Site's Contact Us Us</button>
</div>
</form>
@if(count($errors))
<div class="alert alert-danger">
<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>
</div>
@endif
@endsection

resources/views/admin/editFAQS.blade.php
@extends('admin.master')
@section('content')

<form method="POST" action="/admin/updateFAQS/{{ $faq->id }}"  enctype="multipart/form-data">
	{{ csrf_field() }}
  <input type="hidden" name="_method" value="PATCH">
<div class="box box-danger">
            <div class="box-header with-border">
              <h3 class="box-title">Edit Site FAQ</h3>
            </div>
	<div class="form-group has-success">
	  <label class="control-label" for="inputSuccess"><i class="fa fa-check"></i> Question</label>
	  <input type="text" class="form-control" name="question" id="inputSuccess" value="{{ $faq->question }}">
	  <span class="help-block">Must Be Deep &amp; Decribtive</span>
	</div>
   <div class="box box-info">
    <div class="box-header">
      <h3 class="box-title">Answer
      </h3>
      <div class="pull-right box-tools">
        <button type="button" class="btn btn-info btn-sm" data-widget="collapse" data-toggle="tooltip"
                title="Collapse">
          <i class="fa fa-minus"></i></button>
        <button type="button" class="btn btn-danger btn-sm" data-widget="remove" data-toggle="tooltip"
                title="Remove">
          <i class="fa fa-times"></i></button>
      </div>
    </div>
    <div class="box-body pad">
            <textarea id="editor1" name="answer" rows="10" cols="80">{{ $faq->answer }}
            </textarea>
    </div>
  </div>
<div class="box-footer">
<button type="submit" class="btn btn-success btn-block btn-flat">Edit Site's FAQ</button>
</div>
</form>
@if(count($errors))
<div class="alert alert-danger">
<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>
</div>
@endif
@endsection

resources/views/admin/editSiteInfo.blade.php
@extends('admin.master')
@section('content')

<form method="POST" action="/admin/updateSiteInfo/{{ $info->id }}"  enctype="multipart/form-data">
	{{ csrf_field() }}
  <input type="hidden" name="_method" value="PATCH">
<div class="box box-danger">
            <div class="box-header with-border">
              <h3 class="box-title">Edit Site Information</h3>
            </div>
	<div class="form-group has-success">
	  <label class="control-label" for="inputSuccess"><i class="fa fa-check"></i> Site Name</label>
	  <input type="text" class="form-control" name="site_name" id="inputSuccess" value="{{ $info->site_name }}">
	  <span class="help-block">Must Choose Special &amp; Unique Site Name</span>
	</div>
	<div class="form-group has-error">
    <label class="control-label" for="inputError"><i class="fa fa-times-circle-o"></i> Site Key Words</label>
    <input name="key_words" type="text" class="form-control" id="inputError" value="{{ $info->key_words }}">
    <span class="help-block">Will appear in google search</span>
  </div>
  <hr>
  <div class="row">
      <div class="col-xs-4">  
        <h5>Old Site Logo</h5>
      <img src="/public/site_info/{{ $info->logo }}" width="215">
      </div>
      <div class="col-xs-8">  
        <label>Upload new site logo</label>
        <input type="file" name="logo" class="form-control">
      </div>
  </div>
  <hr>
  <div class="row">
      <div class="col-xs-4">  
        <h5>Old Site Fivicon</h5>
      <img src="/public/site_info/{{ $info->fivicon }}" width="215">
      </div>
      <div class="col-xs-8">  
        <label>Upload new site Fivicon</label>
        <input type="file" name="fivicon" class="form-control">
      </div>
  </div>
  <hr>
  <div class="form_group">
    <label>Description</label>
    <input name="description" class="form-control input-lg" type="text" value="{{ $info->description }}">
  </div>
  <br>
  <div class="row">
      <div class="col-xs-3">  
        <label>Author</label>
        <input name="author" type="text" class="form-control" value="{{ $info->author }}">
      </div>
      <div class="col-xs-4">  
        <label>Policy</label>
        <textarea name="policy" class="form-control" rows="3">{{ $info->policy }}
        </textarea>
      </div>

      <div class="box box-info">
        <div class="box-header">
          <h3 class="box-title">Website Uses
          </h3>
          <div class="pull-right box-tools">
            <button type="button" class="btn btn-info btn-sm" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-danger btn-sm" data-widget="remove" data-toggle="tooltip"
                    title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body pad">
                <textarea id="editor1" name="website_used" rows="10" cols="80">
                     {{ $info->website_used }}
                </textarea>
        </div>
      </div>
      </div>
  <br>
  <div class="row">
      <div class="col-xs-6">  
        <label>Payment Methods</label>
        <textarea name="payment_methods" class="form-control" rows="3">{{ $info->payment_methods }}
        </textarea>
      </div>
      <div class="col-xs-6">  
        <label>Footer About</label>
        <textarea name="footer_about" class="form-control" rows="3">{{ $info->footer_about }}
        </textarea>
      </div>
  </div>
  <br>
  <div class="row">
      <div class="col-xs-3">  
        <label>Facebook Acc.</label>
        <input name="fb" type="text" class="form-control" value="{{ $info->fb }}">
      </div>
      <div class="col-xs-3">  
        <label>Twitter Acc.</label>
          <input name="tw" type="text" class="form-control" value="{{ $info->tw }}">
      </div>
      <div class="col-xs-3">  
        <label>Instagram Acc.</label>
        <input name="instagram" type="text" class="form-control" value="{{ $info->instagram }}">
      </div>
      <div class="col-xs-3">  
        <label>Google Acc.</label>
        <input name="google" type="text" class="form-control" value="{{ $info->google }}">
      </div>
  </div>
  <br>
   <div class="box box-info">
    <div class="box-header">
      <h3 class="box-title">Kasam
      </h3>
      <div class="pull-right box-tools">
        <button type="button" class="btn btn-info btn-sm" data-widget="collapse" data-toggle="tooltip"
                title="Collapse">
          <i class="fa fa-minus"></i></button>
        <button type="button" class="btn btn-danger btn-sm" data-widget="remove" data-toggle="tooltip"
                title="Remove">
          <i class="fa fa-times"></i></button>
      </div>
    </div>
    <div class="box-body pad">
            <textarea id="editor1" name="term_docx" rows="10" cols="80">
                  {{ $info->term_docx }}
            </textarea>
    </div>
  </div>
<div class="box-footer">
<button type="submit" class="btn btn-success btn-block btn-flat">Edit Site's Info</button>
</div>
</form>
@if(count($errors))
<div class="alert alert-danger">
<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>
</div>
@endif
@endsection

resources/views/admin/fagsUsShow.blade.php
@extends('admin.master')
@section('content')
@if($flash = session('message'))
<div class="alert success">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
    <b>{{ $flash }}</b>
</div>
@endif
@if($flash = session('deleted'))
<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
    <b>{{ $flash }}</b>
</div>
@endif

<div class="box">
            <div class="box-header">
  <h3 class="box-title">Data Table For Frequently Asked Questions</h3>
</div>
    <div class="box-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>ID</th>
          <th>Question</th>
          <th>Answer</th>
          <th>Edit</th>
        </tr>
        </thead>
        <tbody>
@foreach($faqs as $faq)
        <tr>
          <td>{{ $faq->id }}</td>
          <td>{{ $faq->question }}</td>
          <td><?= $faq->answer ?></td>
          <td>
            <a href="/admin/edit_faqs/{{ $faq->id }}" class="btn btn-app">
                 <i class="fa fa-edit"></i> Edit
            </a>
            <a href="/admin/delete_faq/{{ $faq->id }}" class="btn btn-app">
                 <i class="fa fa-close"></i> Delete
            </a>
          </td>
        </tr>
@endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/admin/forExcel.blade.php
@extends('admin.master')
@section('content')
@php
  $do = (isset($_GET['do'])) ? $_GET['do'] : 'blocked' ;
@endphp
<style>
    .exportExcel{
  padding: 5px;
  border: 1px solid grey;
  margin: 5px;
  cursor: pointer;
}
</style>

<div class="box">
            <div class="box-header">
  <h3 class="box-title">Data Table For Not Approved Users</h3>
</div>
            <div class="box-body">
              <table id="example3" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>ID</th>
                  <th>Username</th>
                  <th>Full Name</th>
                  <th>Email</th>
                  <th>Phone Number</th>
                  <th>MemberShip</th>
                  <th>Registered At</th>
                </tr>
                </thead>
                <tbody>
@foreach($users as $user)
                <tr>
                  <td>{{ $user->id }}</td>
                  <td>{{ $user->username }}</td>
                  <td>{{ $user->fname }} {{ $user->lname }}</td>
                  <td>{{ $user->email }}</td>
                  <td>{{ $user->phone }}</td>
                  <td>{{ $user->member_ship }}</td>
                  <td>{{ $user->created_at }}</td>
                </tr>
@endforeach
                </tbody>
              </table>
            </div>
          </div>
@endsection