routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');
Route::get('index','FrontController@index');
Route::get('register','FrontController@register');
//Route::get('login','FrontController@lo');
Route::get('maleRegister','FrontController@MaleRegisterForm');
Route::post('maleRegister','FrontController@MaleRegister');
Route::get('femaleRegister','FrontController@FemaleRegisterForm');
Route::post('femaleRegister','FrontController@FemaleRegister');
Route::get('city/{id}','FrontController@city');
Route::get('email/{id}','FrontController@email');
Route::get('username/{id}','FrontController@username');
Route::get('phone/{id}','FrontController@phone');
Route::get('salary/{id}','FrontController@salary');
Route::get('height/{id}','FrontController@height');
Route::get('weight/{id}','FrontController@weight');
Route::post('/client/home','ClientAuth\LoginController@login');
Route::get('/test','FrontController@pricesValues');
Route::get('liked', 'FrontController@likes');
Route::get('blocked', 'FrontController@blocked');
Route::get('/cancelBlock/{id}', 'LikesController@cancelBlock');
Route::get('/search', 'FastSearchController@search');
Route::get('/profile_views/{id}', 'ProfileViewController@addView');

  Route::get('/admin/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
  Route::post('/admin/login', 'AdminAuth\LoginController@login');

Route::group(['prefix' => 'admin', 'middleware'=>'admin'], function () {
  Route::get('/logout', 'AdminAuth\LoginController@logout')->name('logout');
  Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'AdminAuth\RegisterController@register');

  //clients
  Route::get('/users', 'dashboard\ClientsController@index');
  Route::get('/approve/{id}', 'dashboard\ClientsController@approve');
  Route::get('/unapprove/{id}', 'dashboard\ClientsController@block');
  Route::get('/upgrage/{id}', 'dashboard\ClientsController@upgrage');
  Route::get('/details/{id}', 'dashboard\ClientsController@show');
  Route::get('/edit_user/{id}', 'dashboard\ClientsController@edit');
  Route::patch('/updateUser/{id}', 'dashboard\ClientsController@update');
  Route::get('/fakeData', 'dashboard\ClientsController@fakers');
  Route::get('/country', 'dashboard\ClientsController@country');
  Route::get('/delete/{id}', 'dashboard\ClientsController@destroy');
  Route::get('/country/city/{id}', 'dashboard\ClientsController@city');
  Route::get('/all_users', 'dashboard\ClientsController@forExcel');

  //messages
  Route::get('/send_message/{id}', 'dashboard\MessageToClientsController@index');
  Route::get('/send/message', 'dashboard\MessageToClientsController@sendMessage');

  //site info
  Route::get('/site_info', 'dashboard\SiteInfoController@index');
  Route::get('/add_site_info', 'dashboard\SiteInfoController@create');
  Route::get('/edit_info/{id}', 'dashboard\SiteInfoController@edit');
  Route::get('/delete_info/{id}', 'dashboard\SiteInfoController@destroy');
  Route::patch('/updateSiteInfo/{id}', 'dashboard\SiteInfoController@update');

  //about us
  Route::get('/about-us', 'dashboard\OtherSiteInfoController@showAboutUs');
  Route::get('/edit_about_us/{id}', 'dashboard\OtherSiteInfoController@editAboutUs');
  Route::patch('/updateAboutUs/{id}', 'dashboard\OtherSiteInfoController@updateAboutUs');

  //Contact us
  Route::get('/contact_us', 'dashboard\OtherSiteInfoController@showContactUs');
  Route::get('/edit_contact_us/{id}', 'dashboard\OtherSiteInfoController@editContactUs');
  Route::patch('/updateContactUs/{id}', 'dashboard\OtherSiteInfoController@updateContactUs');

  //FAQS
  Route::get('/faqs', 'dashboard\OtherSiteInfoController@showFAQ');
  Route::get('/edit_faqs/{id}', 'dashboard\OtherSiteInfoController@editFAQ');
  Route::patch('/updateFAQS/{id}', 'dashboard\OtherSiteInfoController@updateFAQ');
  Route::get('/createFaqs', 'dashboard\OtherSiteInfoController@createFAQ');
  Route::post('/storeFaq', 'dashboard\OtherSiteInfoController@storeFAQ');
  Route::get('/delete_faq/{id}', 'dashboard\OtherSiteInfoController@destroyFaq');

  //MailBox
  Route::get('/mailbox', 'dashboard\MessageToClientsController@seeAll');
  Route::get('/message', 'MailController@index');

  Route::resource('mail', 'MailController');


  //resets
  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');

  Route::resource('country','CountryController');
  Route::resource('city','CityController');
});

Route::group(['prefix' => 'client'], function () {
  // Route::post('/login', 'ClientAuth\LoginController@login');
  Route::get('/logout', 'ClientAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'ClientAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'ClientAuth\RegisterController@register');

  Route::get('/edit', 'UserController@edit');
  Route::patch('/update/{id}', 'UserController@update');

  Route::get('/contact', 'dashboard\MessageToClientsController@showForm');
  Route::post('/toAdmin', 'dashboard\MessageToClientsController@postContact');

  Route::get('/faq', 'CityController@FAQ');
  Route::get('/profile/{id}', 'FrontController@profile');
  //messages
  Route::get('/message', 'UserController@showCoversations');
  Route::get('/message/{id}', 'UserController@viewMessages');
  Route::post('/message', 'UserController@sendMessage');

  
  Route::get('/nsay7', 'CityController@advice');
  Route::get('/country/city/{id}', 'dashboard\ClientsController@city');

  //add like
  Route::get('/like/{id}', 'LikesController@addLike');

  //add block
  Route::get('/block/{id}', 'LikesController@addBlock');

  //visits
  Route::get('/visits','ProfileViewController@visits');
  
  //Advanced Search
  Route::get('/advanced_search', 'FastSearchController@advanced_search');
  Route::get('/AS', 'FastSearchController@advanced_search_results');
  
  Route::post('/password/email', 'ClientAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'ClientAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'ClientAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'ClientAuth\ResetPasswordController@showResetForm');
});

resources/views/admin/layout/auth.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel Multi Auth Guard') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/admin') }}">
                    {{ config('app.name', 'Laravel Multi Auth Guard') }}: Admin
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/admin/login') }}">Login</a></li>
                        <li><a href="{{ url('/admin/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('/admin/logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/admin/layout/footer.blade.php
    </div>
    </section>
    </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>GTSAW Panel</b> V-2.2.0
    </div>
    <strong>Copyright &copy; {{ date('Y') }} <a href="http://gtsaw.com/">GTSAW</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="/bower_components/jquery/dist/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="/bower_components/raphael/raphael.min.js"></script>
<script src="/bower_components/morris.js/morris.min.js"></script>
<!-- Sparkline -->
<script src="/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/bower_components/moment/min/moment.min.js"></script>
<script src="/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- Slimscroll -->
<script src="/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>
<!-- DataTables -->
<script src="/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.min.js"></script>
<script src="/dist/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>
<!-- page script -->
<script src="/bower_components/ckeditor/ckeditor.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>

<script src="//cdn.datatables.net/buttons/1.2.1/js/buttons.html5.min.js"></script>
<script>
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('editor1')
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5()
  })
</script>
<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable()
  })
</script>
<script>
   $(document).ready(function() {
  var table = $('#example3').DataTable({
    dom: 'Bfrtip',
    buttons: [
    {
      extend: 'excel',
      text: 'Export Excel',
      className: 'exportExcel',
      filename: 'Users_report',
      exportOptions: {
        modifier: {
          page: 'all'
        }
      }
    }]
  });

});
</script>

<script type="text/javascript">
  $(document).ready(function(){
    $("#country").on('change',function(){
      var id = $("#country").val();
      $.ajax({
      type: "GET",
      url: '/admin/country/city/' + id,
      data: {},
      success: function( msg ) {
        $("#cityDisplay").fadeIn(1000);
        $("#city").html(msg.message);

      },
      dataType: "json"
  });

    });

    $("#gender").on('change',function(){
       var gender = $("#gender").val();
       if(gender === 'female')
       {
        $("#marraige12").fadeOut(1000);
       }
       else
       {
        $("#marraige12").fadeIn(1000);
       }
    });

      $("#social_single").on('change',function(){
       var social_single = $("#social_single").val();
       if(social_single === 'single')
       {
        $("#numberChild").fadeOut(1000);
        $("#marraige12").fadeOut(1000);
       }
       else
       {
         $("#numberChild").fadeIn(1000);
        $("#marraige12").fadeIn(1000);
       }
    });




  });


</script>
</body>
</html>

resources/views/admin/layout/sidebar.blade.php
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ Auth::guard('admin')->user()->username }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i>
            <span>Clients</span>
            <span class="pull-right-container">
              @php
                $count = App\Client::count();
              @endphp
              <span class="label label-primary pull-right">{{ $count }}</span>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="/admin/users"><i class="fa fa-circle-o"></i> Show Clients</a></li>
            <li><a href="/admin/fakeData"><i class="fa fa-circle-o"></i> Add Fake 10 Users</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i>
            <span>Countries & Cities</span>
            <span class="pull-right-container">
              <span class="label label-primary pull-right">{{ App\Country::count()  }}</span>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ route('country.create') }}"><i class="fa fa-circle-o"></i> Add Country</a></li>
            <li><a href="{{ route('city.create') }}"><i class="fa fa-circle-o"></i> Add Cities</a></li>
            <li><a href="{{ route('country.index') }}"><i class="fa fa-circle-o"></i> Show All Countries & Cities </a></li>
          </ul>
        </li>
          <ul class="treeview-menu">
            <li class="active"><a href="/admin/home"><i class="fa fa-circle-o"></i>Dashboard</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i>
            <span>Client Chats</span>
            <span class="pull-right-container">
              @php
                  $count = App\Mail::distinct('sender_id')->count('sender_id');
              @endphp
              <span class="label label-primary pull-right">{{ $count }}</span>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="/admin/message"><i class="fa fa-circle-o"></i> All Clients Messages</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-laptop"></i>
            <span>Site Information</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="/admin/site_info"><i class="fa fa-circle-o"></i> View Information</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-share"></i> <span>Other Sections In Site</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="/admin/about-us"><i class="fa fa-circle-o"></i> About Us</a></li>
            <li class="treeview">
              <a href="#"><i class="fa fa-circle-o"></i> FAQ
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="/admin/faqs"><i class="fa fa-circle-o"></i> Show FAQ</a></li>
                <li><a href="/admin/createFaqs"><i class="fa fa-circle-o"></i> Add FAQs</a></li>
              </ul>
            </li>
            <li><a href="/admin/contact_us"><i class="fa fa-circle-o"></i> Contact Us</a></li>
          </ul>
        </li>
        @php
        $seen_count = App\AdminToClientMessages::where('is_admin', 'no')->where('is_read', 'seen')->count();

        $message_count = App\AdminToClientMessages::where('is_admin', 'no')->where('is_read', 'unseen')->count();

        $total_count = App\AdminToClientMessages::count();

        @endphp
        <li>
          <a href="/admin/mailbox">
            <i class="fa fa-envelope"></i> <span>Mailbox</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-yellow">{{ $seen_count }}</small>
              <small class="label pull-right bg-green">{{ $total_count }}</small>
              <small class="label pull-right bg-red">{{ $message_count }}</small>
            </span>
          </a>
        </li>
        
        <!--<li><a href="https://adminlte.io/docs"><i class="fa fa-book"></i> <span>Documentation</span></a></li>-->
        <li class="header">LABELS</li>
        <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <div class="content-wrapper">